### ISSUE TITLE
Windows 7. Replace files.

### ISSUE THREAD

**Issue by harryray33** [crystalidea/qt6windows7#10]
Could you explain this please?

Is this simply a case of replacing qt6 files, with these files to make something run on Win 7, or is it more involved than that.

For example, I have a programme, CopyQ version 8 which doesn't run on Win 7. It has various QT6 files.
Can I just replace the original QT6 files, with your QT6 files?

Hope that makes sense.

Thanks

**Comment by i486** [comment]
> Could you explain this please?
> 
> Is this simply a case of replacing qt6 files, with these files to make something run on Win 7, or is it more involved than that.
> 
> For example, I have a programme, CopyQ version 8 which doesn't run on Win 7. It has various QT6 files. Can I just replace the original QT6 files, with your QT6 files?
> 
> Hope that makes sense.
> 
> Thanks

Works fine with https://github.com/vxiiduu/VxKex/

**Comment by sergeevabc** [comment]
Indeed, we need an example that people can follow.

For example, there is a personal accounting app [Eqonomize](https://github.com/Eqonomize/Eqonomize) by @hanna-kn. By default its x64 version is provided with QT6 libraries. If I unpack all your files, for example, from release https://github.com/crystalidea/qt6windows7/releases/tag/v6.8.1 on top of her files, then her app runs on Windows 7 without errors. However, this way does not seem to be the optimal, because your archive contains 44 MB of various files. Are they all really necessary?
