### ISSUE TITLE
QT 6.4.3

### ISSUE THREAD

**Issue by i486** [crystalidea/qt6windows7#4]
Do you mind doing same for 6.4.3? 

I have a some apps that stuck on using 6.4.3 and i'd love to use the update on my Win 7 box.

**Comment by kleuter** [comment]
I don't have 6.4.3 tag in the repository... But the problem is that these DLLs still require Microsoft libraries from Visual C++ 2019, particulary 

"api-ms-win-core-console-l1-1-0.dll""
"api-ms-win-core-console-l1-2-0.dll""
"api-ms-win-core-datetime-l1-1-0.dll""
"api-ms-win-core-debug-l1-1-0.dll""
"api-ms-win-core-errorhandling-l1-1-0.dll""
"api-ms-win-core-file-l1-1-0.dll""
"api-ms-win-core-file-l1-2-0.dll""
"api-ms-win-core-file-l2-1-0.dll""
"api-ms-win-core-handle-l1-1-0.dll""
"api-ms-win-core-heap-l1-1-0.dll""
"api-ms-win-core-interlocked-l1-1-0.dll""
"api-ms-win-core-libraryloader-l1-1-0.dll""
"api-ms-win-core-localization-l1-2-0.dll""
"api-ms-win-core-memory-l1-1-0.dll""
"api-ms-win-core-namedpipe-l1-1-0.dll""
"api-ms-win-core-processenvironment-l1-1-0.dll""
"api-ms-win-core-processthreads-l1-1-0.dll""
"api-ms-win-core-processthreads-l1-1-1.dll""
"api-ms-win-core-profile-l1-1-0.dll""
"api-ms-win-core-rtlsupport-l1-1-0.dll""
"api-ms-win-core-string-l1-1-0.dll""
"api-ms-win-core-synch-l1-1-0.dll""
"api-ms-win-core-synch-l1-2-0.dll""
"api-ms-win-core-sysinfo-l1-1-0.dll""
"api-ms-win-core-timezone-l1-1-0.dll""
"api-ms-win-core-util-l1-1-0.dll""
"API-MS-Win-core-xstate-l2-1-0.dll""
"api-ms-win-crt-conio-l1-1-0.dll""
"api-ms-win-crt-convert-l1-1-0.dll""
"api-ms-win-crt-environment-l1-1-0.dll""
"api-ms-win-crt-filesystem-l1-1-0.dll""
"api-ms-win-crt-heap-l1-1-0.dll""
"api-ms-win-crt-locale-l1-1-0.dll""
"api-ms-win-crt-math-l1-1-0.dll""
"api-ms-win-crt-multibyte-l1-1-0.dll""
"api-ms-win-crt-private-l1-1-0.dll""
"api-ms-win-crt-process-l1-1-0.dll""
"api-ms-win-crt-runtime-l1-1-0.dll""
"api-ms-win-crt-stdio-l1-1-0.dll""
"api-ms-win-crt-string-l1-1-0.dll""
"api-ms-win-crt-time-l1-1-0.dll""
"api-ms-win-crt-utility-l1-1-0.dll""
"concrt140.dll""
"msvcp140.dll""
"msvcp140_1.dll""
"msvcp140_2.dll""
"msvcp140_atomic_wait.dll""
"msvcp140_codecvt_ids.dll""
"ucrtbase.dll""
"vccorlib140.dll""
"vcruntime140.dll""

What you need is basically compile Qt yourself

**Comment by i486** [comment]
I just want to confirm if I understand correctly. Are the DLLs you listed essentially the same as those from the Microsoft Visual C++ 2015-2022 Redistributable packages, which can be installed on Windows 7? In other words, would installing the C++ Redistributable on my Windows 7 machine not be sufficient for the DLLs to work, or is there a specific difference in the build process?

I'm a dual user of both Windows 10 and 7. Some of the software I rely on, which was working seamlessly on Windows 7, stopped functioning after a recent update. I discovered that the issue was related to an update in their QT components to version 6.xx, which dropped support for Windows 7. Fortunately, I found the QT6 on Windows 7 thread and was able to download the DLL package shared by dmginc. Replacing the DLLs in the application directory resolved the problem, and the application is now running perfectly on Windows 7. I've been following a similar process whenever the app updates, replacing the QT DLLs accordingly.

Recently, I encountered a similar issue with another application stuck on an older version on my PC due to the same QT6 problem. This time, the app uses version 6.4.3, and unfortunately, there are no "Windows 7" compatible DLLs of this version shared on the QT6 on Windows 7 thread.

Given that you're the last active user on that forum who shared the new Windows7-DLLs and are using a similar approach as the thread but with many improvements, I reached out, hoping for DLLs for the 6.4.3 version.

Regarding compiling, I must admit that I'm not a programmer. Even if I manage to successfully install Visual Studio or a similar tool, I'm uncertain about applying the necessary patches, etc. I attempted to compile an app before but eventually gave up after encountering compile errors and spending hours trying to install prerequisites like libraries.
